name: Run Daily Menu Scraper

on:
  schedule:
    - cron: '0 4 * * *'  # 12:00 AM Eastern Time = 4:00 AM UTC
  workflow_dispatch:     

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      BACK4APP_APP_ID: JYuuToLFr527wvq3Be7oWjWgA86bvvrIridk2kC6
      BACK4APP_REST_API_KEY: 4zyD4yvlZO0Mz3QJF0EJHvIqflZWxWA0OF5sfIaj
      BACK4APP_MASTER_KEY: gQsAz4ZUd9Xe0TlXakaxIJ3giYmHqMzw1Yi3duVs
      BACK4APP_SERVER_URL: https://parseapi.back4app.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scripts/get_menu_back4app.py
